package hashtable.easy;

import java.util.HashMap;
import java.util.Map;

public class _389_Find_the_Difference {

    /**
     * Given two strings s and t which consist of only lowercase letters.
     *
     * String t is generated by random shuffling string s and then add one more letter at a random position.
     *
     * Find the letter that was added in t.
     *
     * Example:
     *
     * Input:
     * s = "abcd"
     * t = "abcde"
     *
     * Output:
     * e
     *
     * Explanation:
     * 'e' is the letter that was added.
     *
     *
     *
     * 弱逼hashmap.
     */

    public char findTheDifference(String s, String t) {
        //map (char, cnt); !contain, or cnt == 0
        Map<Character, Integer> map = new HashMap<>();
        char[] arr = s.toCharArray();
        for (Character ch : arr) {
            int cnt = map.getOrDefault(ch, 0);
            map.put(ch, cnt + 1);
        }
        char[] arr1 = t.toCharArray();
        for (Character ch : arr1) {
            if (map.containsKey(ch)) {
                int cnt = map.get(ch);
                if (cnt == 0) return ch;
                map.put(ch, cnt - 1);
            } else {
                return ch;
            }
        }
        return '\0';
    }
}
